### ISSUE TITLE
Support custom URL schemes for both Inbound/Outbound (ex: OpenIn)

### ISSUE THREAD

**Issue by StellarRedditApp** [StellarReddit/Features#16]
Add support for URL schemes (option for modified or unmodified) so apps like OpenIn can redirect URLs to system apps.

Similarly, accept URLs and open them directly in Stellar.

**Comment by StellarRedditApp** [comment]
Use the scheme `stellar:https://...` to open links directly in Stellar.

**Comment by electr1fy0** [comment]
This needs the app to be running already.
Is it possible that it opens the page even when the app is not opened already?

The current behaviour is it just launching the home page in stellar if the app is already not open.

**Comment by StellarRedditApp** [comment]
Thank you for reporting this bug. We are able to reproduce this, and will do some more testing and try to have a fix out for Stellar 88 (2.3.1.)

**Comment by StellarRedditApp** [comment]
All right, this is fixed as of Stellar 88 (2.3.1.) Thanks again for reporting!

**Comment by electr1fy0** [comment]
Wow, that was quick!
