### ISSUE TITLE
Reordering items in sidebar

### ISSUE THREAD

**Issue by podhy** [StellarReddit/Features#27]
Hi, it would be nice to be able reorder items in sidebar. E.g. I would like to have on top positions "My multi-reddits" which are now under Subscriptions.

**Comment by aciodev** [comment]
This is a feature in the next update - The Stellar Anniversary Edition 2.0. Checkout the subreddit this Monday, July 18, for a development update and timeline!

**Comment by StellarRedditApp** [comment]
Thank you for the feature request.
