### ISSUE TITLE
dialogs lose focus 

### ISSUE THREAD

**Issue by dpreschel** [StellarReddit/Features#42]
This may be by design,  but asking. Dialog boxes,  like the account manager,  are not "always on top" - not sure what the correct term is,  but they lose focus if you click elsewhere.   Then if you try opening it again via the menu,  you get nothing,  because it's already open in the background.  Hope this makes sense,  probably didn't explain very well!

**Comment by StellarRedditApp** [comment]
Thank you for the user experience feedback! There is probably some method to bring the window in the background back to focus. We will research this and include the update soon. Likely in Stellar 2.0.4, as Stellar 2.0.3 is in pre-release mode at the moment.

**Comment by StellarRedditApp** [comment]
This is a feature as of Stellar 2.0.4.
