### ISSUE TITLE
Added account does not appear in quick switch menu

### ISSUE THREAD

**Issue by digitalself** [StellarReddit/Features#45]
I have added my second account to Stellar multiple times, and although it shows in the "Feeds" window and the Preferences>Accounts window, it does not show in the Quick Switch menu. I've restarted, deleted and re-added, nothing has helped. Running the latest release.

**Comment by StellarRedditApp** [comment]
Are you a Pro user? Multiple accounts is a Pro feature.

**Comment by digitalself** [comment]
> 

I am not a Pro, user, but I am obviously an idiot as i didn't spot that anywhere. Apologies, will buy Pro as the app is definitely worth it. Cheers

**Comment by StellarRedditApp** [comment]
Thank you for following-up! This confusion is understandable, as the "Choose Account" menu doesn't make it clear that multiple accounts is a paid feature. We will make some quality of life improvements to make it clearer.

Thank you for purchasing Pro! Every purchase helps drive our development further. If you have any feature requests or issues, please do not hesitate to reach out.
